os: Visual Studio 2017

version: "{build}-{branch}"

cache:
  - C:\Users\appveyor\.cargo
  - target

install:
  - appveyor DownloadFile https://win.rustup.rs/ -FileName rustup-init.exe
  - rustup-init -yv
  - set PATH=%PATH%;%USERPROFILE%\.cargo\bin
  - rustc -vV
  - cargo -vV
  - rustup component add rustfmt
  - rustfmt --version

build: false

test_script:
  - cargo fmt -- --check
  - cargo build --release
  - cargo test --release

after_test:
  - 7z a svg_to_ico.7z .\target\release\svg_to_ico.exe README.md

artifacts:
  - path: svg_to_ico.7z
    name: svg_to_ico

deploy:
  - provider: GitHub
    tag: $(APPVEYOR_REPO_TAG_NAME)
    release: svg_to_ico v$(APPVEYOR_REPO_TAG_NAME)
    description: "The `.7z` archive contains a Windows binary and the `.tar.xz` archive contains a Linux binary statically linked against musl for increased portability."
    auth_token:
      secure: V1GojGQfrAiQtUWtNNXfm3samiH+1yNF5UYhkn8B8mbif20IGTGWNlBS9E4S0SUC
    artifact: svg_to_ico
    draft: false
    force_update: true
    on:
      appveyor_repo_tag: true
