name: CI

on: [push, pull_request]

env:
  CARGO_TERM_COLOR: always

jobs:
  rustfmt:
    runs-on: ubuntu-18.04
    steps:
      - uses: actions/checkout@v2

      - name: Install Rustfmt
        run: |
          rustup component add rustfmt
          rustfmt --version
      - name: Check formatting
        run: cargo fmt --all -- --check

  windows:
    runs-on: windows-2019
    steps:
      - uses: actions/checkout@v2

      - uses: actions/cache@v2
        with:
          path: |
            ~/.cargo/registry
            ~/.cargo/git
            target
          key: ${{ runner.os }}-cargo-${{ hashFiles('**/Cargo.lock') }}

      - name: Build & test
        run: cargo test
